version: '3.8'
services:
  database:
    container_name: big-food-database
    image: bitnami/postgresql:latest
    environment:
      PRODUCTION: 'false'
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DATABASE: ${TYPEORM_DATABASE}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - ${TYPEORM_PORT}:5432
